### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by DarlanJurak** [jan-dolejsi/vscode-pddl#18]
I've just installed jan-dolejsi.pddl and when i try to do anything i receive the following messages:

command 'pddl.configurePlanner' not found
command 'pddl.planAndDisplayResult' not found
command 'pddl.configureParser' not found
command 'pddl.tests.view' not found

...

I think there is a problem with the installation.

OS: 
Ubuntu 16.04

vscode v: 
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by jan-dolejsi** [comment]
Hi! Sorry I missed the message here. If the extension is installed and enabled (you need to push the _Reload_ button appearing in place of the _Install_ button when the extension successfully installs or otherwise restart VS Code), it is configured to be activated by many different conditions:

```json
  "activationEvents": [
    "onLanguage:pddl",
    "onLanguage:plan",
    "onLanguage:happenings",
    "workspaceContains:**/*.pddl",
    "workspaceContains:**/*ptest.json",
    "onCommand:pddl.configureParser",
    "onCommand:pddl.configurePlanner"
  ]
```

The usual way of activation is that your workspace includes a _.pddl_ file or a file that you manually select the language for as _PDDL_ (bottom right in the status bar). Or you trigger the _PDDL: Configure planner.._ or _PDDL: Configure parser_ commands.

The extension is not activated all the time to shorten the start-up time and memory footprint.

Please confirm if this was/not helpful.

**Comment by jan-dolejsi** [comment]
Thanks. That is interesting. That means the extension does not start successfully on your system. Does VS Code indicate that something crashed? 
Can you please check if you see the extension in the list invoked by running the Developer: Show Running Extensions command?

**Comment by JonIsAmazingYa** [comment]
I have the same issue, running on Lubuntu 18.10 :(

**Comment by jan-dolejsi** [comment]
Thanks all for the supporting info. I believe I found the problem (case insensitive node.js imports) in the extension code. I managed to test it on Ubuntu 18.10. Please retry - the new version of the extension should download automatically, you will need to re-open VS Code to make the upgrade effective.

I ran the blocksworld STRIPS domain/problem using the default cloud planner and it worked. However, I noticed some differences in the plan visualization. 

Please let me know if I can now close this issue and if you find other problems, please let me know.

**Comment by DarlanJurak** [comment]
![image](https://user-images.githubusercontent.com/5911696/47466463-aca8af80-d7c7-11e8-98cc-a93879d931db.png)
![image](https://user-images.githubusercontent.com/5911696/47466501-d7930380-d7c7-11e8-9f19-39b70cd1f35b.png)
![image](https://user-images.githubusercontent.com/5911696/47466514-e7124c80-d7c7-11e8-9a59-728d75115086.png)
![image](https://user-images.githubusercontent.com/5911696/47466519-ef6a8780-d7c7-11e8-8896-782ecd2f8c23.png)
![screenshot from 2018-10-24 20-04-22](https://user-images.githubusercontent.com/5911696/47466653-a0712200-d7c8-11e8-94c3-27179fbbdb68.png)
![image](https://user-images.githubusercontent.com/5911696/47466666-b0890180-d7c8-11e8-9e5e-331400bce2af.png)

**Comment by jan-dolejsi** [comment]
Alright, let's dig deeper. Can you please select the menu _Help > Toggle Developer Tools_ item?

A panel opens up from the right with a console at the bottom. 

If you scroll up in the console, you should see some startup and extension activation messages, namely 

`[Extension Host] Activating extension 'jan-dolejsi.pddl' failed:`

Can you see any?

**Comment by JonIsAmazingYa** [comment]
Jan,

Output regarding the extension from the developer tools;

[Extension Host] Activating extension ‘jan-dolejsi.pddl’ failed: Cannot find module ‘./Plan’.

[Extension Host] Activating extension ‘jan-dolejsi.pddl’ failed: Cannot find module ‘./Plan’

Here is the error stack:  Error: Cannot find module './Plan'
     at Function.Module._resolveFilename (module.js:543:15)
     at Function.Module._load (module.js:473:25)
     at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:655:268)
     at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:563)
     at Module.require (module.js:586:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/home/jon/.vscode/extensions/jan-dolejsi.pddl-2.6.11/out/common/src/PddlPlanParser.js:7:16)
     at Object.<anonymous> (/home/jon/.vscode/extensions/jan-dolejsi.pddl-2.6.11/out/common/src/PddlPlanParser.js:152:3)
     at Module._compile (module.js:642:30)
     at Object.Module._extensions..js (module.js:653:10)
     at Module.load (module.js:561:32)
     at tryModuleLoad (module.js:504:12)
     at Function.Module._load (module.js:496:3)
     at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:655:268)
     at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:563)
     at Module.require (module.js:586:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/home/jon/.vscode/extensions/jan-dolejsi.pddl-2.6.11/out/common/src/parser.js:10:26)
     at Object.<anonymous> (/home/jon/.vscode/extensions/jan-dolejsi.pddl-2.6.11/out/common/src/parser.js:577:3)
     at Module._compile (module.js:642:30)
     at Object.Module._extensions..js (module.js:653:10)
     at Module.load (module.js:561:32)
     at tryModuleLoad (module.js:504:12)
     at Function.Module._load (module.js:496:3)
     at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:655:268)

...it continues...

Is this helpful?


Jon

**Comment by jan-dolejsi** [comment]
Thanks. If anyone still has an extension activation issue, please open a new issue.
